    <option value="Afghanistan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Afghanistan')); ?>>Afghanistan</option>
    <option value="Albania" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Albania')); ?>>Albania</option>
    <option value="Algeria" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Algeria')); ?>>Algeria</option>
    <option value="American Samoa" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'American Samoa')); ?>>American Samoa</option>
    <option value="Andorra" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Andorra')); ?>>Andorra</option>
    <option value="Angola" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Angola')); ?>>Angola</option>
    <option value="Anguilla" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Anguilla')); ?>>Anguilla</option>
    <option value="Antartica" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Antartica')); ?>>Antarctica</option>
    <option value="Antigua and Barbuda" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Antigua and Barbuda')); ?>>Antigua and Barbuda</option>
    <option value="Argentina" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Argentina')); ?>>Argentina</option>
    <option value="Armenia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Armenia')); ?>>Armenia</option>
    <option value="Aruba" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Aruba')); ?>>Aruba</option>
    <option value="Australia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Australia')); ?>>Australia</option>
    <option value="Austria" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Austria')); ?>>Austria</option>
    <option value="Azerbaijan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Azerbaijan')); ?>>Azerbaijan</option>
    <option value="Bahamas" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bahamas')); ?>>Bahamas</option>
    <option value="Bahrain" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bahrain')); ?>>Bahrain</option>
    <option value="Bangladesh" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bangladesh')); ?>>Bangladesh</option>
    <option value="Barbados" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Barbados')); ?>>Barbados</option>
    <option value="Belarus" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Belarus')); ?>>Belarus</option>
    <option value="Belgium" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Belgium')); ?>>Belgium</option>
    <option value="Belize" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Belize')); ?>>Belize</option>
    <option value="Benin" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Benin')); ?>>Benin</option>
    <option value="Bermuda" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bermuda')); ?>>Bermuda</option>
    <option value="Bhutan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bhutan')); ?>>Bhutan</option>
    <option value="Bolivia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bolivia')); ?>>Bolivia</option>
    <option value="Bosnia and Herzegowina" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bosnia and Herzegowina')); ?>>Bosnia and Herzegowina</option>
    <option value="Botswana" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Botswana')); ?>>Botswana</option>
    <option value="Bouvet Island" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bouvet Island')); ?>>Bouvet Island</option>
    <option value="Brazil" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Brazil')); ?>>Brazil</option>
    <option value="British Indian Ocean Territory" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'British Indian Ocean Territory')); ?>>British Indian Ocean Territory</option>
    <option value="Brunei Darussalam" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Brunei Darussalam')); ?>>Brunei Darussalam</option>
    <option value="Bulgaria" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Bulgaria')); ?>>Bulgaria</option>
    <option value="Burkina Faso" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Burkina Faso')); ?>>Burkina Faso</option>
    <option value="Burundi" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Burundi')); ?>>Burundi</option>
    <option value="Cambodia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cambodia')); ?>>Cambodia</option>
    <option value="Cameroon" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cameroon')); ?>>Cameroon</option>
    <option value="Canada" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Canada')); ?>>Canada</option>
    <option value="Cape Verde" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cape Verde')); ?>>Cape Verde</option>
    <option value="Cayman Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cayman Islands')); ?>>Cayman Islands</option>
    <option value="Central African Republic" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Central African Republic')); ?>>Central African Republic</option>
    <option value="Chad" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Chad')); ?>>Chad</option>
    <option value="Chile" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Chile')); ?>>Chile</option>
    <option value="China" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'China')); ?>>China</option>
    <option value="Christmas Island" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Christmas Island')); ?>>Christmas Island</option>
    <option value="Cocos Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cocos Islands')); ?>>Cocos (Keeling) Islands</option>
    <option value="Colombia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Colombia')); ?>>Colombia</option>
    <option value="Comoros" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Comoros')); ?>>Comoros</option>
    <option value="Congo" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Congo')); ?>>Congo</option>
    <option value="Congo" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Congo')); ?>>Congo, the Democratic Republic of the</option>
    <option value="Cook Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cook Islands')); ?>>Cook Islands</option>
    <option value="Costa Rica" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Costa Rica')); ?>>Costa Rica</option>
    <option value="Cota D`Ivoire" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cota D`Ivoire')); ?>>Cote d'Ivoire</option>
    <option value="Croatia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Croatia')); ?>>Croatia (Hrvatska)</option>
    <option value="Cuba" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cuba')); ?>>Cuba</option>
    <option value="Cyprus" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Cyprus')); ?>>Cyprus</option>
    <option value="Czech Republic" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Czech Republic')); ?>>Czech Republic</option>
    <option value="Denmark" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Denmark')); ?>>Denmark</option>
    <option value="Djibouti" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Djibouti')); ?>>Djibouti</option>
    <option value="Dominica" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Dominica')); ?>>Dominica</option>
    <option value="Dominican Republic" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Dominican Republic')); ?>>Dominican Republic</option>
    <option value="East Timor" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'East Timor')); ?>>East Timor</option>
    <option value="Ecuador" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Ecuador')); ?>>Ecuador</option>
    <option value="Egypt" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Egypt')); ?>>Egypt</option>
    <option value="El Salvador" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'El Salvador')); ?>>El Salvador</option>
    <option value="Equatorial Guinea" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Equatorial Guinea')); ?>>Equatorial Guinea</option>
    <option value="Eritrea" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Eritrea')); ?>>Eritrea</option>
    <option value="Estonia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Estonia')); ?>>Estonia</option>
    <option value="Ethiopia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Ethiopia')); ?>>Ethiopia</option>
    <option value="Falkland Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Falkland Islands')); ?>>Falkland Islands (Malvinas)</option>
    <option value="Faroe Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Faroe Islands')); ?>>Faroe Islands</option>
    <option value="Fiji" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Fiji')); ?>>Fiji</option>
    <option value="Finland" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Finland')); ?>>Finland</option>
    <option value="France" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'France')); ?>>France</option>
    <option value="France Metropolitan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'France Metropolitan')); ?>>France, Metropolitan</option>
    <option value="French Guiana" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'French Guiana')); ?>>French Guiana</option>
    <option value="French Polynesia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'French Polynesia')); ?>>French Polynesia</option>
    <option value="French Southern Territories" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'French Southern Territories')); ?>>French Southern Territories</option>
    <option value="Gabon" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Gabon')); ?>>Gabon</option>
    <option value="Gambia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Gambia')); ?>>Gambia</option>
    <option value="Georgia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Georgia')); ?>>Georgia</option>
    <option value="Germany" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Germany')); ?>>Germany</option>
    <option value="Ghana" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Ghana')); ?>>Ghana</option>
    <option value="Gibraltar" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Gibraltar')); ?>>Gibraltar</option>
    <option value="Greece" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Greece')); ?>>Greece</option>
    <option value="Greenland" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Greenland')); ?>>Greenland</option>
    <option value="Grenada" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Grenada')); ?>>Grenada</option>
    <option value="Guadeloupe" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Guadeloupe')); ?>>Guadeloupe</option>
    <option value="Guam" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Guam')); ?>>Guam</option>
    <option value="Guatemala" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Guatemala')); ?>>Guatemala</option>
    <option value="Guinea" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Guinea')); ?>>Guinea</option>
    <option value="Guinea-Bissau" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Guinea-Bissau')); ?>>Guinea-Bissau</option>
    <option value="Guyana" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Guyana')); ?>>Guyana</option>
    <option value="Haiti" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Haiti')); ?>>Haiti</option>
    <option value="Heard and McDonald Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Heard and McDonald Islands')); ?>>Heard and Mc Donald Islands</option>
    <option value="Holy See" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Holy See')); ?>>Holy See (Vatican City State)</option>
    <option value="Honduras" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Honduras')); ?>>Honduras</option>
    <option value="Hong Kong" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Hong Kong')); ?>>Hong Kong</option>
    <option value="Hungary" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Hungary')); ?>>Hungary</option>
    <option value="Iceland" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Iceland')); ?>>Iceland</option>
    <option value="India" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'India')); ?>>India</option>
    <option value="Indonesia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Indonesia')); ?>>Indonesia</option>
    <option value="Iran" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Iran')); ?>>Iran (Islamic Republic of)</option>
    <option value="Iraq" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Iraq')); ?>>Iraq</option>
    <option value="Ireland" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Ireland')); ?>>Ireland</option>
    <option value="Israel" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Israel')); ?>>Israel</option>
    <option value="Italy" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Italy')); ?>>Italy</option>
    <option value="Jamaica" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Jamaica')); ?>>Jamaica</option>
    <option value="Japan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Japan')); ?>>Japan</option>
    <option value="Jordan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Jordan')); ?>>Jordan</option>
    <option value="Kazakhstan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Kazakhstan')); ?>>Kazakhstan</option>
    <option value="Kenya" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Kenya')); ?>>Kenya</option>
    <option value="Kiribati" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Kiribati')); ?>>Kiribati</option>
    <option value="Democratic People`s Republic of Korea" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Democratic People`s Republic of Korea')); ?>>Korea, Democratic People's Republic of</option>
    <option value="Korea" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Korea')); ?>>Korea, Republic of</option>
    <option value="Kuwait" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Kuwait')); ?>>Kuwait</option>
    <option value="Kyrgyzstan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Kyrgyzstan')); ?>>Kyrgyzstan</option>
    <option value="Lao" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Lao')); ?>>Lao People's Democratic Republic</option>
    <option value="Latvia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Latvia')); ?>>Latvia</option>
    <option value="Lebanon" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Lebanon')); ?>>Lebanon</option>
    <option value="Lesotho" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Lesotho')); ?>>Lesotho</option>
    <option value="Liberia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Liberia')); ?>>Liberia</option>
    <option value="Libyan Arab Jamahiriya" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Libyan Arab Jamahiriya')); ?>>Libyan Arab Jamahiriya</option>
    <option value="Liechtenstein" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Liechtenstein')); ?>>Liechtenstein</option>
    <option value="Lithuania" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Lithuania')); ?>>Lithuania</option>
    <option value="Luxembourg" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Luxembourg')); ?>>Luxembourg</option>
    <option value="Macau" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Macau')); ?>>Macau</option>
    <option value="Macedonia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Macedonia')); ?>>Macedonia, The Former Yugoslav Republic of</option>
    <option value="Madagascar" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Madagascar')); ?>>Madagascar</option>
    <option value="Malawi" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Malawi')); ?>>Malawi</option>
    <option value="Malaysia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Malaysia')); ?>>Malaysia</option>
    <option value="Maldives" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Maldives')); ?>>Maldives</option>
    <option value="Mali" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Mali')); ?>>Mali</option>
    <option value="Malta" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Malta')); ?>>Malta</option>
    <option value="Marshall Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Marshall Islands')); ?>>Marshall Islands</option>
    <option value="Martinique" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Martinique')); ?>>Martinique</option>
    <option value="Mauritania" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Mauritania')); ?>>Mauritania</option>
    <option value="Mauritius" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Mauritius')); ?>>Mauritius</option>
    <option value="Mayotte" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Mayotte')); ?>>Mayotte</option>
    <option value="Mexico" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Mexico')); ?>>Mexico</option>
    <option value="Micronesia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Micronesia')); ?>>Micronesia, Federated States of</option>
    <option value="Moldova" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Moldova')); ?>>Moldova, Republic of</option>
    <option value="Monaco" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Monaco')); ?>>Monaco</option>
    <option value="Mongolia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Mongolia')); ?>>Mongolia</option>
    <option value="Montserrat" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Montserrat')); ?>>Montserrat</option>
    <option value="Morocco" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Morocco')); ?>>Morocco</option>
    <option value="Mozambique" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Mozambique')); ?>>Mozambique</option>
    <option value="Myanmar" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Myanmar')); ?>>Myanmar</option>
    <option value="Namibia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Namibia')); ?>>Namibia</option>
    <option value="Nauru" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Nauru')); ?>>Nauru</option>
    <option value="Nepal" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Nepal')); ?>>Nepal</option>
    <option value="Netherlands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Netherlands')); ?>>Netherlands</option>
    <option value="Netherlands Antilles" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Netherlands Antilles')); ?>>Netherlands Antilles</option>
    <option value="New Caledonia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'New Caledonia')); ?>>New Caledonia</option>
    <option value="New Zealand" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'New Zealand')); ?>>New Zealand</option>
    <option value="Nicaragua" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Nicaragua')); ?>>Nicaragua</option>
    <option value="Niger" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Niger')); ?>>Niger</option>
    <option value="Nigeria" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Nigeria')); ?>>Nigeria</option>
    <option value="Niue" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Niue')); ?>>Niue</option>
    <option value="Norfolk Island" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Norfolk Island')); ?>>Norfolk Island</option>
    <option value="Northern Mariana Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Northern Mariana Islands')); ?>>Northern Mariana Islands</option>
    <option value="Norway" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Norway')); ?>>Norway</option>
    <option value="Oman" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Oman')); ?>>Oman</option>
    <option value="Pakistan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Pakistan')); ?>>Pakistan</option>
    <option value="Palau" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Palau')); ?>>Palau</option>
    <option value="Panama" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Panama')); ?>>Panama</option>
    <option value="Papua New Guinea" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Papua New Guinea')); ?>>Papua New Guinea</option>
    <option value="Paraguay" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Paraguay')); ?>>Paraguay</option>
    <option value="Peru" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Peru')); ?>>Peru</option>
    <option value="Philippines" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Philippines')); ?>>Philippines</option>
    <option value="Pitcairn" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Pitcairn')); ?>>Pitcairn</option>
    <option value="Poland" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Poland')); ?>>Poland</option>
    <option value="Portugal" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Portugal')); ?>>Portugal</option>
    <option value="Puerto Rico" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Puerto Rico')); ?>>Puerto Rico</option>
    <option value="Qatar" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Qatar')); ?>>Qatar</option>
    <option value="Reunion" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Reunion')); ?>>Reunion</option>
    <option value="Romania" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Romania')); ?>>Romania</option>
    <option value="Russia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Russia')); ?>>Russian Federation</option>
    <option value="Rwanda" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Rwanda')); ?>>Rwanda</option>
    <option value="Saint Kitts and Nevis" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Saint Kitts and Nevis')); ?>>Saint Kitts and Nevis</option> 
    <option value="Saint LUCIA" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Saint LUCIA')); ?>>Saint LUCIA</option>
    <option value="Saint Vincent" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Saint Vincent')); ?>>Saint Vincent and the Grenadines</option>
    <option value="Samoa" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Samoa')); ?>>Samoa</option>
    <option value="San Marino" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'San Marino')); ?>>San Marino</option>
    <option value="Sao Tome and Principe" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Sao Tome and Principe')); ?>>Sao Tome and Principe</option> 
    <option value="Saudi Arabia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Saudi Arabia')); ?>>Saudi Arabia</option>
    <option value="Senegal" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Senegal')); ?>>Senegal</option>
    <option value="Seychelles" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Seychelles')); ?>>Seychelles</option>
    <option value="Sierra" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Sierra')); ?>>Sierra Leone</option>
    <option value="Singapore" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Singapore')); ?>>Singapore</option>
    <option value="Slovakia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Slovakia')); ?>>Slovakia (Slovak Republic)</option>
    <option value="Slovenia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Slovenia')); ?>>Slovenia</option>
    <option value="Solomon Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Solomon Islands')); ?>>Solomon Islands</option>
    <option value="Somalia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Somalia')); ?>>Somalia</option>
    <option value="South Africa" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'South Africa')); ?>>South Africa</option>
    <option value="South Georgia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'South Georgia')); ?>>South Georgia and the South Sandwich Islands</option>
    <option value="Span" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Span')); ?>>Spain</option>
    <option value="SriLanka" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'SriLanka')); ?>>Sri Lanka</option>
    <option value="St. Helena" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'St. Helena')); ?>>St. Helena</option>
    <option value="St. Pierre and Miguelon" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'St. Pierre and Miguelon')); ?>>St. Pierre and Miquelon</option>
    <option value="Sudan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Sudan')); ?>>Sudan</option>
    <option value="Suriname" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Suriname')); ?>>Suriname</option>
    <option value="Svalbard" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Svalbard')); ?>>Svalbard and Jan Mayen Islands</option>
    <option value="Swaziland" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Swaziland')); ?>>Swaziland</option>
    <option value="Sweden" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Sweden')); ?>>Sweden</option>
    <option value="Switzerland" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Switzerland')); ?>>Switzerland</option>
    <option value="Syria" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Syria')); ?>>Syrian Arab Republic</option>
    <option value="Taiwan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Taiwan')); ?>>Taiwan, Province of China</option>
    <option value="Tajikistan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Tajikistan')); ?>>Tajikistan</option>
    <option value="Tanzania" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Tanzania')); ?>>Tanzania, United Republic of</option>
    <option value="Thailand" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Thailand')); ?>>Thailand</option>
    <option value="Togo" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Togo')); ?>>Togo</option>
    <option value="Tokelau" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Tokelau')); ?>>Tokelau</option>
    <option value="Tonga" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Tonga')); ?>>Tonga</option>
    <option value="Trinidad and Tobago" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Trinidad and Tobago')); ?>>Trinidad and Tobago</option>
    <option value="Tunisia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Tunisia')); ?>>Tunisia</option>
    <option value="Turkey" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Turkey')); ?>>Turkey</option>
    <option value="Turkmenistan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Turkmenistan')); ?>>Turkmenistan</option>
    <option value="Turks and Caicos" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Turks and Caicos')); ?>>Turks and Caicos Islands</option>
    <option value="Tuvalu" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Tuvalu')); ?>>Tuvalu</option>
    <option value="Uganda" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Uganda')); ?>>Uganda</option>
    <option value="Ukraine" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Ukraine')); ?>>Ukraine</option>
    <option value="United Arab Emirates" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'United Arab Emirates')); ?>>United Arab Emirates</option>
    <option value="United Kingdom" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'United Kingdom')); ?>>United Kingdom</option>
    <option value="United States" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'United States')); ?>>United States</option>
    <option value="United States Minor Outlying Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'United States Minor Outlying Islands')); ?>>United States Minor Outlying Islands</option>
    <option value="Uruguay" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Uruguay')); ?>>Uruguay</option>
    <option value="Uzbekistan" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Uzbekistan')); ?>>Uzbekistan</option>
    <option value="Vanuatu" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Vanuatu')); ?>>Vanuatu</option>
    <option value="Venezuela" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Venezuela')); ?>>Venezuela</option>
    <option value="Vietnam" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Vietnam')); ?>>Viet Nam</option>
    <option value="Virgin Islands (British)" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Virgin Islands (British)')); ?>>Virgin Islands (British)</option>
    <option value="Virgin Islands (U.S)" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Virgin Islands (U.S)')); ?>>Virgin Islands (U.S.)</option>
    <option value="Wallis and Futana Islands" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Wallis and Futana Islands')); ?>>Wallis and Futuna Islands</option>
    <option value="Western Sahara" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Western Sahara')); ?>>Western Sahara</option>
    <option value="Yemen" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Yemen')); ?>>Yemen</option>
    <option value="Yugoslavia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Yugoslavia')); ?>>Yugoslavia</option>
    <option value="Zambia" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Zambia')); ?>>Zambia</option>
    <option value="Zimbabwe" <?php echo e(runtimePreselected($task->task_custom_field_5 ?? '', 'Zimbabwe')); ?>>Zimbabwe</option><?php /**PATH /home/livecrm/public_html/application/resources/views/misc/pickup-country-list.blade.php ENDPATH**/ ?>